# Count and Say#
#     Problem: The "count-and-say" sequence is a sequence of digits, starting with 1.
#     Each subsequent term is generated by describing the digits of the previous term.
#     Example: For n = 4, the sequence is "1211", which is read as "one 1, one 2, two 1s".

def count_and_say(n):
    result = "1"
    for _ in range(n - 1):
        temp = ""
        count = 1
        for i in range(1, len(result)):
            if result[i] == result[i - 1]:
                count += 1
            else:
                temp += str(count) + result[i - 1]
                count = 1
        temp += str(count) + result[-1]
        result = temp
    return result

# Example usage:
print(count_and_say(4))  # Output: "1211"
